---
title: "Refugee Analysis"
output: 
  flexdashboard::flex_dashboard:
    social: menu
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(highcharter)
library(shiny)
library(FactoMineR)
library(mclust)
library(tidyr)
library(dplyr)

hchart.cor <- function(object, ...) {
  
  df <- as.data.frame(object)
  is.num <- sapply(df, is.numeric)
  df[is.num] <- lapply(df[is.num], round, 2)
  dist <- NULL
  
  x <- y <- names(df)
  
  df <- tbl_df(cbind(x = y, df)) %>% 
    gather(y, dist, -x) %>% 
    mutate(x = as.character(x),
           y = as.character(y)) %>% 
    left_join(data_frame(x = y,
                         xid = seq(length(y)) - 1), by = "x") %>% 
    left_join(data_frame(y = y,
                         yid = seq(length(y)) - 1), by = "y")
  
  ds <- df %>% 
    select_("xid", "yid", "dist") %>% 
    list_parse2()
  
  fntltp <- JS("function(){
                  return this.series.xAxis.categories[this.point.x] + ' ~ ' +
                         this.series.yAxis.categories[this.point.y] + ': <b>' +
                         Highcharts.numberFormat(this.point.value, 2)+'</b>';
               ; }")
  cor_colr <- list( list(0, '#F8F5F5'),
                    list(1, '#2E86C1')
  )
  highchart() %>% 
    hc_chart(type = "heatmap") %>% 
    hc_yAxis(categories = y, title = list(text="")) %>% 
    hc_xAxis(categories = y, title = list(text="")) %>% 
    hc_add_series(data = ds) %>% 
    hc_plotOptions(
           series = list(
             boderWidth = 0,
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(formatter = fntltp) %>% 
    hc_legend(align = "right", layout = "vertical",
              margin = 5, horizontalAlign = "top",
              y = -70,x=0, symbolWidth=10,symbolHeight=500) %>% 
    hc_colorAxis(  stops= cor_colr,min=0,max=1)
}

# refugee <- readxl::read_xlsx("./Refugee Camp Data Analysis (working file) - Copy v2.xlsx")
# colnames(refugee)<-gsub("Percentage_","PERCENT_",colnames(refugee))
# refugee$`Open date`<-as.POSIXct(refugee$`Open date`)
# refugee$`Population date`<-as.POSIXct(refugee$`Population date`)
# 
# 
# refugee_data<-data.frame(refugee[,which(colSums(apply(refugee,2,is.na))==0)])
# proper_refugee_data<-refugee_data[!unlist(lapply(refugee_data,is.numeric))]
# 
# refugee_format <- as.vector(unlist(lapply(refugee_data,is.numeric)))
# 
# ID_refugee_camp <- refugee_data$Accommodation.Type==c("Refugee Camp")
# ID_IDP_settlement <- refugee_data$Accommodation.Type==c("IDP Settlement")
# ID_community_settlement <- refugee_data$Accommodation.Type==c("Community Settlement")
# ID_status_open <- refugee_data$Condition == c("Open")
# ID_status_closed <- refugee_data$Condition == c("Closed")
# 
# numerical_refugee_data<-refugee_data[,refugee_format]
# categorical_from_numerical<-apply(numerical_refugee_data,2,function(X){
#   mclust::Mclust(X,x=mclust::mclustBIC(X))$classification
# })
# 
# 
# 
# MCA___refugee_camp___status_open <- MCA(
#   data.frame(
#   proper_refugee_data,
#   apply(categorical_from_numerical,2,as.factor))[as.logical(ID_refugee_camp*ID_status_open),],ncp = 2)
# 
# MCA___refugee_camp___status_closed <- MCA(
#   data.frame(
#   proper_refugee_data,
#   apply(categorical_from_numerical,2,as.factor))[as.logical(ID_refugee_camp*ID_status_closed),],ncp = 2)
# 
# MCA___refugee_camp <- MCA(
#   data.frame(
#   proper_refugee_data,
#   apply(categorical_from_numerical,2,as.factor))[ID_refugee_camp,],ncp = 2)
# 
# 
# MCA___IDP_settlement <- MCA(
#   data.frame(
#   proper_refugee_data,
#   apply(categorical_from_numerical,2,as.factor))[ID_IDP_settlement,],ncp = 2)
# 
# 
# MCA___community_settlement <- MCA(
#   data.frame(
#   proper_refugee_data,
#   apply(categorical_from_numerical,2,as.factor))[ID_community_settlement,],ncp = 2)



load("./main.RData")


for_open.date_as.y_NUM<-(as.matrix(numerical_refugee_data[,-c(12,14,16,18,20,22)]))

dgmm_model<-deepgmm::model_selection(y=scale(for_open.date_as.y_NUM),layers = 2,g=3,seeds = 1)
refugee_cluster<-cbind(apply(dgmm_model$fit$s,1,function(X){paste0(X,collapse = "_")}),refugee)

table(refugee_cluster$`apply(dgmm_model$fit$s, 1, function(X) {`,refugee_cluster$`Accommodation Type`)

plot(umap_model,col=refugee_cluster$`apply(dgmm_model$fit$s, 1, function(X) {`)


colnames(for_open.date_as.y_NUM)<-colnames(numerical_refugee_data[,-c(1:10,12,14,16,18,20,22)])
  
for_open.date_as.y_CAT<-proper_refugee_data[,-c(1,3,7:21)]


IDS<-sample(c(1:dim(for_open.date_as.y_CAT)[1]),floor(0.7*dim(for_open.date_as.y_CAT)[1]))
for_open.date_as.y_CAT_train<-for_open.date_as.y_CAT[IDS,]
for_open.date_as.y_NUM_train<-for_open.date_as.y_NUM[IDS,]
for_open.date_as.y_CAT_test<-for_open.date_as.y_CAT[-IDS,]
for_open.date_as.y_NUM_test<-for_open.date_as.y_NUM[-IDS,]

for_open.date_as.y<-as.data.frame(cbind(for_open.date_as.y_CAT_train,for_open.date_as.y_NUM_train))

open.date_lmer<-lme4::lmer(as.integer(proper_refugee_data$Open.date)[IDS]~
                             Male+
                             Female+
                             X0.to.11+
                             X12.to.17+
                             X18.to.59+
                             X60.plus+
                             (1|(Accommodation.Type))+
                             (1|(Accommodation.Type):(Region):(Country))                           ,data=for_open.date_as.y)

pred<-predict(open.date_lmer,data.frame(for_open.date_as.y_NUM_test,for_open.date_as.y_CAT_test),allow.new.levels=T,type="response")



test_lmer<-as.POSIXct(pred,origin = "1970-01-01 00:00.00 UTC")
check<-data.frame(test_lmer,refugee$`Open date`[-IDS])


plot(check$test_lmer~check$refugee..Open.date.)
mean(sqrt((as.numeric(substr(check$test_lmer,0,4))-as.numeric(substr(check$refugee..Open.date.,0,4)))^2))
sd(sqrt((as.numeric(substr(check$test_lmer,0,4))-as.numeric(substr(check$refugee..Open.date.,0,4)))^2))


test<-data.frame(for_open.date_as.y_NUM_test,for_open.date_as.y_CAT_test)[10,]
test[1:6]<-test[1:6]*0.1
as.POSIXct(predict(open.date_lmer,test,allow.new.levels=T),origin = "1970-01-01 00:00.00 UTC")


```


Refugee Camp
=======================================================================

Column {data-width=900 .tabset} 
-------------------------------------

### Explaining Variables

```{r}

  renderHighchart({
    
    using_data <- MCA___refugee_camp
    id_selection <- rep(T,length(ID_refugee_camp))
    
    if (input$status_variables=="Open"){
      using_data <- MCA___refugee_camp___status_open
      id_selection <- as.logical(ID_status_open*ID_refugee_camp)
    }
    if (input$status_variables=="Closed"){
      using_data <- MCA___refugee_camp___status_closed
      id_selection <- as.logical(ID_status_closed*ID_refugee_camp)
    }
    if (input$status_variables=="All"){
      using_data <- MCA___refugee_camp
      id_selection <- as.logical(ID_refugee_camp)
    }
    
    data_MCA<-using_data[['var']][['eta2']]
    data_MCA<-data.frame(data_MCA)
    colnames(data_MCA)<-c('x','y')
    data_MCA$grvar<-c(colnames(proper_refugee_data),colnames(categorical_from_numerical))
    data_MCA$color <- colorize(as.factor(c(colnames(proper_refugee_data),colnames(categorical_from_numerical))),colors = c(RColorBrewer::brewer.pal(n = 12, name = 'Paired'),RColorBrewer::brewer.pal(n = 12, name = 'Set3'),RColorBrewer::brewer.pal(n = 8, name = 'Set2'),RColorBrewer::brewer.pal(n = 9, name = 'Set1'),RColorBrewer::brewer.pal(n = 8, name = 'Pastel2'),RColorBrewer::brewer.pal(n = 9, name = 'Pastel1')
)
)

    collect_id<-grep(paste0("^",input$collect_variables_refugee,"$",collapse="|"),c(colnames(proper_refugee_data),colnames(categorical_from_numerical)))
    
    data_MCA<-data_MCA[collect_id,]
    
  hc <- hchart(data_MCA,type="scatter",hcaes(x=x,y=y,group=grvar),dataLabels = list(enabled = TRUE, format='{point.grvar}'),showInLegend=F) %>% hc_tooltip(pointFormat = "{point.grvar}")
  
  
  hc %>% hc_size(height = 2000) 
  hc %>% hc_colors(data_MCA$color)
  
  hc
  
  }) 


```



### Variable Similarity 
```{r}

  renderHighchart({
    
    using_data <- MCA___refugee_camp
    id_selection <- rep(T,length(ID_refugee_camp))
    
    if (input$status_variables=="Open"){
      using_data <- MCA___refugee_camp___status_open
      id_selection <- as.logical(ID_status_open*ID_refugee_camp)
    }
    if (input$status_variables=="Closed"){
      using_data <- MCA___refugee_camp___status_closed
      id_selection <- as.logical(ID_status_closed*ID_refugee_camp)
    }
    if (input$status_variables=="All"){
      using_data <- MCA___refugee_camp
      id_selection <- as.logical(ID_refugee_camp)
    }
    
    data_MCA<-using_data[['var']][['eta2']]
    data_MCA<-data.frame(data_MCA)
    
    collect_id<-grep(paste0("^",input$collect_variables_refugee,"$",collapse="|"),c(colnames(proper_refugee_data),colnames(categorical_from_numerical)))
    
    to_heat_map<-(as.matrix(dist(data_MCA,method = "euclidean"))/sqrt(2))[collect_id,collect_id]
    index_to_heat<-heatmap(to_heat_map)$rowInd
    
    hchart.cor(to_heat_map[index_to_heat,index_to_heat])
    
  }) 


```


### Variable Collection

```{r}
selectInput(inputId = "status_variables",
                   label = "Status",
            choices = c("All","Open","Closed"))

selectInput(inputId = "collect_variables_refugee",
                   label = "Collect variables",
            choices = c(colnames(refugee_data)),multiple = T,selectize = T,selected =  c(colnames(refugee_data)))

```


Column {.tabset}
-------------------------------------

### Variable Selection


```{r}
selectInput(inputId = "select_variables_A1",
                   label = "Choose variable",
            choices = colnames(refugee_data), selected = colnames(refugee_data)[1])

selectInput(inputId = "select_variables_A2",
                   label = "Choose variable",
            choices = colnames(refugee_data), selected = colnames(refugee_data)[2])

selectInput(inputId = "select_variables_A3",
                   label = "Choose variable",
            choices = colnames(refugee_data), selected = colnames(refugee_data)[3])

selectInput(inputId = "select_variables_A4",
                   label = "Choose variable",
            choices = colnames(refugee_data), selected = colnames(refugee_data)[4])


```

### Analysis_1


```{r}

  renderHighchart({
    
    using_data <- MCA___refugee_camp
    id_selection <- rep(T,length(ID_refugee_camp))
    
    if (input$status_variables=="Open"){
      using_data <- MCA___refugee_camp___status_open
      id_selection <- as.logical(ID_status_open*ID_refugee_camp)
    }
    if (input$status_variables=="Closed"){
      using_data <- MCA___refugee_camp___status_closed
      id_selection <- as.logical(ID_status_closed*ID_refugee_camp)
    }
    if (input$status_variables=="All"){
      using_data <- MCA___refugee_camp
      id_selection <- as.logical(ID_refugee_camp)
    }
  
    data_MCA<-using_data[['svd']][['U']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$color = colorize(refugee_data[[input$select_variables_A1]][id_selection])
    data_MCA$group = paste(refugee_data[["Name"]][id_selection],":   ",refugee_data[[input$select_variables_A1]][id_selection],sep=" ")

    highchart() %>% 
    hc_chart(type = "scatter") %>% 
    hc_add_series_scatter( x = data_MCA$x, y = data_MCA$y, labels = data_MCA$group, color = data_MCA$color) %>% 
    hc_plotOptions(
           series = list(
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(pointFormat = "{point.labels}")%>%
    hc_title(text=as.character(input$select_variables_A1))
    
  })


```





### Analysis_2

```{r}



  renderHighchart({
    
    using_data <- MCA___refugee_camp
    id_selection <- rep(T,length(ID_refugee_camp))
    
    if (input$status_variables=="Open"){
      using_data <- MCA___refugee_camp___status_open
      id_selection <- as.logical(ID_status_open*ID_refugee_camp)
    }
    if (input$status_variables=="Closed"){
      using_data <- MCA___refugee_camp___status_closed
      id_selection <- as.logical(ID_status_closed*ID_refugee_camp)
    }
    if (input$status_variables=="All"){
      using_data <- MCA___refugee_camp
      id_selection <- as.logical(ID_refugee_camp)
    }
  
    data_MCA<-using_data[['svd']][['U']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$color = colorize(refugee_data[[input$select_variables_A2]][id_selection])
    data_MCA$group = paste(refugee_data[["Name"]][id_selection],":   ",refugee_data[[input$select_variables_A2]][id_selection],sep=" ")


    highchart() %>% 
    hc_chart(type = "scatter") %>% 
    hc_add_series_scatter( x = data_MCA$x, y = data_MCA$y, labels = data_MCA$group, color = data_MCA$color) %>% 
    hc_plotOptions(
           series = list(
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(pointFormat = "{point.labels}") %>%
    hc_title(text=as.character(input$select_variables_A2))
    
  
  })

```





### Analysis_3

```{r}

  renderHighchart({
    
    using_data <- MCA___refugee_camp
    id_selection <- rep(T,length(ID_refugee_camp))
    
    if (input$status_variables=="Open"){
      using_data <- MCA___refugee_camp___status_open
      id_selection <- as.logical(ID_status_open*ID_refugee_camp)
    }
    if (input$status_variables=="Closed"){
      using_data <- MCA___refugee_camp___status_closed
      id_selection <- as.logical(ID_status_closed*ID_refugee_camp)
    }
    if (input$status_variables=="All"){
      using_data <- MCA___refugee_camp
      id_selection <- as.logical(ID_refugee_camp)
    }
  
    data_MCA<-using_data[['svd']][['U']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$color = colorize(refugee_data[[input$select_variables_A3]][id_selection])
    data_MCA$group = paste(refugee_data[["Name"]][id_selection],":   ",refugee_data[[input$select_variables_A3]][id_selection],sep=" ")


    highchart() %>% 
    hc_chart(type = "scatter") %>% 
    hc_add_series_scatter( x = data_MCA$x, y = data_MCA$y, labels = data_MCA$group, color = data_MCA$color) %>% 
    hc_plotOptions(
           series = list(
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(pointFormat = "{point.labels}")%>%
    hc_title(text=as.character(input$select_variables_A3))
    
  })


```





### Analysis_4

```{r}

  renderHighchart({
    
    using_data <- MCA___refugee_camp
    id_selection <- rep(T,length(ID_refugee_camp))
    
    if (input$status_variables=="Open"){
      using_data <- MCA___refugee_camp___status_open
      id_selection <- as.logical(ID_status_open*ID_refugee_camp)
    }
    if (input$status_variables=="Closed"){
      using_data <- MCA___refugee_camp___status_closed
      id_selection <- as.logical(ID_status_closed*ID_refugee_camp)
    }
    if (input$status_variables=="All"){
      using_data <- MCA___refugee_camp
      id_selection <- as.logical(ID_refugee_camp)
    }
  
    data_MCA<-using_data[['svd']][['U']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$color = colorize(refugee_data[[input$select_variables_A4]][id_selection])
    data_MCA$group = paste(refugee_data[["Name"]][id_selection],":   ",refugee_data[[input$select_variables_A4]][id_selection],sep=" ")


    highchart() %>% 
    hc_chart(type = "scatter") %>% 
    hc_add_series_scatter( x = data_MCA$x, y = data_MCA$y, labels = data_MCA$group, color = data_MCA$color) %>% 
    hc_plotOptions(
           series = list(
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(pointFormat = "{point.labels}")%>%
    hc_title(text=as.character(input$select_variables_A4))
    
  })



```




IDP Settlement
=======================================================================


Column {data-width=900 .tabset}
-------------------------------------


### Explaining Variables

```{r}

  renderHighchart({
    data_MCA<-MCA___IDP_settlement[['var']][['eta2']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$grvar<-c(colnames(proper_refugee_data),colnames(categorical_from_numerical))
    data_MCA$color <- colorize(as.factor(c(colnames(proper_refugee_data),colnames(categorical_from_numerical))),colors = c(RColorBrewer::brewer.pal(n = 12, name = 'Paired'),RColorBrewer::brewer.pal(n = 12, name = 'Set3'),RColorBrewer::brewer.pal(n = 8, name = 'Set2'),RColorBrewer::brewer.pal(n = 9, name = 'Set1'),RColorBrewer::brewer.pal(n = 8, name = 'Pastel2'),RColorBrewer::brewer.pal(n = 9, name = 'Pastel1')
)
)
    
    
    collect_id<-grep(paste0("^",input$collect_variables_IDP,"$",collapse="|"),c(colnames(proper_refugee_data),colnames(categorical_from_numerical)))
    
    data_MCA<-data_MCA[collect_id,]
    
  hc <- hchart(data_MCA,type="scatter",hcaes(x=x,y=y,group=grvar),dataLabels = list(enabled = TRUE, format='{point.grvar}'),showInLegend=F) %>% hc_tooltip(pointFormat = "{point.grvar}")
  
  
  hc %>% hc_size(height = 2000) 
  
  hc
  
  }) 


```



### Variable Similarity

```{r}

  renderHighchart({
    data_MCA<-MCA___IDP_settlement[['var']][['eta2']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)

    collect_id<-grep(paste0("^",input$collect_variables_IDP,"$",collapse="|"),c(colnames(proper_refugee_data),colnames(categorical_from_numerical)))
    
    to_heat_map<-(as.matrix(dist(data_MCA,method = "euclidean"))/sqrt(2))[collect_id,collect_id]
    
    index_to_heat<-heatmap(to_heat_map)$rowInd
    
    hchart.cor(to_heat_map[index_to_heat,index_to_heat])
    
  }) 


```

### Variable Collection

```{r}

selectInput(inputId = "collect_variables_IDP",
                   label = "Collect variables",
            choices = c(colnames(refugee_data)),multiple = T,selectize = T,selected =  c(colnames(refugee_data)))

```





Column {.tabset}
-------------------------------------

### Variable Selection


```{r}
selectInput(inputId = "select_variables_B1",
                   label = "Choose variable",
            choices = colnames(refugee_data), selected = colnames(refugee_data)[1])

selectInput(inputId = "select_variables_B2",
                   label = "Choose variable",
            choices = colnames(refugee_data), selected = colnames(refugee_data)[2])

selectInput(inputId = "select_variables_B3",
                   label = "Choose variable",
            choices = colnames(refugee_data), selected = colnames(refugee_data)[3])

selectInput(inputId = "select_variables_B4",
                   label = "Choose variable",
            choices = colnames(refugee_data), selected = colnames(refugee_data)[4])


```

### Analysis_1


```{r}


  renderHighchart({
  
    data_MCA<-MCA___IDP_settlement[['svd']][['U']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$color = colorize(refugee_data[[input$select_variables_B1]][ID_IDP_settlement])
    data_MCA$group = paste(refugee_data[["Name"]][ID_IDP_settlement],":   ",refugee_data[[input$select_variables_B1]][ID_IDP_settlement],sep=" ")


    highchart() %>% 
    hc_chart(type = "scatter") %>% 
    hc_add_series_scatter( x = data_MCA$x, y = data_MCA$y, labels = data_MCA$group, color = data_MCA$color) %>% 
    hc_plotOptions(
           series = list(
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(pointFormat = "{point.labels}")%>%
    hc_title(text=as.character(input$select_variables_B1))
    
  
  })
```





### Analysis_2

```{r}


  renderHighchart({
  
    data_MCA<-MCA___IDP_settlement[['svd']][['U']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$color = colorize(refugee_data[[input$select_variables_B2]][ID_IDP_settlement])
    data_MCA$group = paste(refugee_data[["Name"]][ID_IDP_settlement],":   ",refugee_data[[input$select_variables_B2]][ID_IDP_settlement],sep=" ")


    highchart() %>% 
    hc_chart(type = "scatter") %>% 
    hc_add_series_scatter( x = data_MCA$x, y = data_MCA$y, labels = data_MCA$group, color = data_MCA$color) %>% 
    hc_plotOptions(
           series = list(
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(pointFormat = "{point.labels}")%>%
    hc_title(text=as.character(input$select_variables_B2))
    
  
  })

```





### Analysis_3

```{r}


  renderHighchart({
  
    data_MCA<-MCA___IDP_settlement[['svd']][['U']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$color = colorize(refugee_data[[input$select_variables_B3]][ID_IDP_settlement])
    data_MCA$group = paste(refugee_data[["Name"]][ID_IDP_settlement],":   ",refugee_data[[input$select_variables_B3]][ID_IDP_settlement],sep=" ")


    highchart() %>% 
    hc_chart(type = "scatter") %>% 
    hc_add_series_scatter( x = data_MCA$x, y = data_MCA$y, labels = data_MCA$group, color = data_MCA$color) %>% 
    hc_plotOptions(
           series = list(
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(pointFormat = "{point.labels}")%>%
    hc_title(text=as.character(input$select_variables_B3))
    
  
  })

```





### Analysis_4

```{r}

  renderHighchart({
  
    data_MCA<-MCA___IDP_settlement[['svd']][['U']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$color = colorize(refugee_data[[input$select_variables_B4]][ID_IDP_settlement])
    data_MCA$group = paste(refugee_data[["Name"]][ID_IDP_settlement],":   ",refugee_data[[input$select_variables_B4]][ID_IDP_settlement],sep=" ")


    highchart() %>% 
    hc_chart(type = "scatter") %>% 
    hc_add_series_scatter( x = data_MCA$x, y = data_MCA$y, labels = data_MCA$group, color = data_MCA$color) %>% 
    hc_plotOptions(
           series = list(
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(pointFormat = "{point.labels}")%>%
    hc_title(text=as.character(input$select_variables_B4))
    
  
  })


```
























Community Settlement
=======================================================================


Column {data-width=900 .tabset}
-------------------------------------


### Explaining Variables

```{r}

  renderHighchart({
    data_MCA<-MCA___community_settlement[['var']][['eta2']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$grvar<-c(colnames(proper_refugee_data),colnames(categorical_from_numerical))
    data_MCA$color <- colorize(as.factor(c(colnames(proper_refugee_data),colnames(categorical_from_numerical))),colors = c(RColorBrewer::brewer.pal(n = 12, name = 'Paired'),RColorBrewer::brewer.pal(n = 12, name = 'Set3'),RColorBrewer::brewer.pal(n = 8, name = 'Set2'),RColorBrewer::brewer.pal(n = 9, name = 'Set1'),RColorBrewer::brewer.pal(n = 8, name = 'Pastel2'),RColorBrewer::brewer.pal(n = 9, name = 'Pastel1')
)
)
    
    collect_id<-grep(paste0("^",input$collect_variables_community,"$",collapse="|"),c(colnames(proper_refugee_data),colnames(categorical_from_numerical)))
    
    data_MCA<-data_MCA[collect_id,]
    
  hc <- hchart(data_MCA,type="scatter",hcaes(x=x,y=y,group=grvar),dataLabels = list(enabled = TRUE, format='{point.grvar}'),showInLegend=F) %>% hc_tooltip(pointFormat = "{point.grvar}")
  
  
  hc %>% hc_size(height = 2000) 
  
  hc
  
  }) 


```



### Variable Similarity

```{r}

  renderHighchart({
    data_MCA<-MCA___community_settlement[['var']][['eta2']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)

    collect_id<-grep(paste0("^",input$collect_variables_community,"$",collapse="|"),c(colnames(proper_refugee_data),colnames(categorical_from_numerical)))
    
    to_heat_map<-(as.matrix(dist(data_MCA,method = "euclidean"))/sqrt(2))[collect_id,collect_id]
    
    index_to_heat<-heatmap(to_heat_map)$rowInd
    
    hchart.cor(to_heat_map[index_to_heat,index_to_heat])
    
  }) 


```

### Variable Collection

```{r}

selectInput(inputId = "collect_variables_community",
                   label = "Collect variables",
            choices = c(colnames(refugee_data)),multiple = T,selectize = T,selected =  c(colnames(refugee_data)))

```



Column {.tabset}
-------------------------------------

### Variable Selection


```{r}
selectInput(inputId = "select_variables_C1",
                   label = "Choose variable",
            choices = colnames(refugee_data), selected = colnames(refugee_data)[1])

selectInput(inputId = "select_variables_C2",
                   label = "Choose variable",
            choices = colnames(refugee_data), selected = colnames(refugee_data)[2])

selectInput(inputId = "select_variables_C3",
                   label = "Choose variable",
            choices = colnames(refugee_data), selected = colnames(refugee_data)[3])

selectInput(inputId = "select_variables_C4",
                   label = "Choose variable",
            choices = colnames(refugee_data), selected = colnames(refugee_data)[4])


```

### Analysis_1


```{r}


  renderHighchart({
  
    data_MCA<-MCA___community_settlement[['svd']][['U']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$color = colorize(refugee_data[[input$select_variables_C1]][ID_community_settlement])
    data_MCA$group = paste(refugee_data[["Name"]][ID_community_settlement],":   ",refugee_data[[input$select_variables_C1]][ID_community_settlement],sep=" ")


    highchart() %>% 
    hc_chart(type = "scatter") %>% 
    hc_add_series_scatter( x = data_MCA$x, y = data_MCA$y, labels = data_MCA$group, color = data_MCA$color) %>% 
    hc_plotOptions(
           series = list(
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(pointFormat = "{point.labels}")%>%
    hc_title(text=as.character(input$select_variables_C1))
    
  
  })
```





### Analysis_2

```{r}


  renderHighchart({
  
    data_MCA<-MCA___community_settlement[['svd']][['U']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$color = colorize(refugee_data[[input$select_variables_C2]][ID_community_settlement])
    data_MCA$group = paste(refugee_data[["Name"]][ID_community_settlement],":   ",refugee_data[[input$select_variables_C2]][ID_community_settlement],sep=" ")


    highchart() %>% 
    hc_chart(type = "scatter") %>% 
    hc_add_series_scatter( x = data_MCA$x, y = data_MCA$y, labels = data_MCA$group, color = data_MCA$color) %>% 
    hc_plotOptions(
           series = list(
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(pointFormat = "{point.labels}")%>%
    hc_title(text=as.character(input$select_variables_C2))
    
  
  })

```





### Analysis_3

```{r}



  renderHighchart({
  
    data_MCA<-MCA___community_settlement[['svd']][['U']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$color = colorize(refugee_data[[input$select_variables_C3]][ID_community_settlement])
    data_MCA$group = paste(refugee_data[["Name"]][ID_community_settlement],":   ",refugee_data[[input$select_variables_C3]][ID_community_settlement],sep=" ")


    highchart() %>% 
    hc_chart(type = "scatter") %>% 
    hc_add_series_scatter( x = data_MCA$x, y = data_MCA$y, labels = data_MCA$group, color = data_MCA$color) %>% 
    hc_plotOptions(
           series = list(
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(pointFormat = "{point.labels}")%>%
    hc_title(text=as.character(input$select_variables_C3))
    
  
  })

```





### Analysis_4

```{r}

  renderHighchart({
  
    data_MCA<-MCA___community_settlement[['svd']][['U']]
    colnames(data_MCA)<-c('x','y')
    data_MCA<-data.frame(data_MCA)
    data_MCA$color = colorize(refugee_data[[input$select_variables_C4]][ID_community_settlement])
    data_MCA$group = paste(refugee_data[["Name"]][ID_community_settlement],":   ",refugee_data[[input$select_variables_C4]][ID_community_settlement],sep=" ")


    highchart() %>% 
    hc_chart(type = "scatter") %>% 
    hc_add_series_scatter( x = data_MCA$x, y = data_MCA$y, labels = data_MCA$group, color = data_MCA$color) %>% 
    hc_plotOptions(
           series = list(
             dataLabels = list(enabled = F)
    )) %>% 
    hc_tooltip(pointFormat = "{point.labels}")%>%
    hc_title(text=as.character(input$select_variables_C4))
  
  })

```


